import os
import time
desktop_path = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')
os.chdir(desktop_path)

os.system("git clone -b Stable https://github.com/HttpAnimation")
os.system("cd FYC-Rewrite-V2")
os.system("del README.md")
os.system("rmdir Templates")
os.system("rm Configs/Replers/README.md")
os.system("rm Modes/README.md")

os.system("curl.exe --output NewWonnix.sh --url https://raw.githubusercontent.com/HttpAnimation/FYC-Rewrite-V2/NodeJSSever/NewWonnix.sh")
os.system("curl.exe --output Run.sh --url https://raw.githubusercontent.com/HttpAnimation/FYC-Rewrite-V2/NodeJSSever/Run.sh")
os.system("curl.exe --output package-lock.json --url https://raw.githubusercontent.com/HttpAnimation/FYC-Rewrite-V2/NodeJSSever/package-lock.json")
os.system("curl.exe --output package.json --url https://raw.githubusercontent.com/HttpAnimation/FYC-Rewrite-V2/NodeJSSever/package.json")
os.system("curl.exe --ouput index.js --url https://raw.githubusercontent.com/HttpAnimation/FYC-Rewrite-V2/NodeJSSever/index.js")

os.system("mv styles.css public")
os.system("mv About.html public")
os.system("mv Credits.html public")
os.system("mv Dev-Classes.html public")
os.system("mv LICENCE public")
os.system("mv Mods.html public")
os.system("mv Q&A.html public")
os.system("mv README.md public")
os.system("mv Updates.html public")
os.system("mv V1-Devs.html public")
os.system("mv Versions.html public")
os.system("mv index.html public")
os.system("mv Configs public")
os.system("mv JS public")
os.system("mv Mods public")
os.system("mv Templates public")
os.system("mv TorrentScripts public")
os.system("mv Report.html public")
os.system("mv Request.html public")
os.system("mv Scripts public")

# os.system("rm Install.py")